---
- hosts: webserver
  remote_user: root
  gather_facts: no
  become: yes
  vars:
    s_name: "webserver"

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create data directory
      file:
        path: /data
        state: directory
        mode: 0755

    - name: Copy vhost file to conf.d
      template:
        src: vhost.conf.j2
        dest: /etc/nginx/conf.d/vhost.conf
        owner: root
        group: root
      notify: Restart nginx

    - name: Change Niginx default port from 80
      replace:
        path: /etc/nginx/nginx.conf
        regexp: 'listen\s+80;'
        replace: "listen 8080;"

      notify: Restart nginx

    - name: Copy index.html file to data dir
      template:
        src: index.html.j2
        dest: /data/index.html
        owner: root
        group: root

    - name: Start Nginx Service
      service:
        name: nginx
        state: started

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
